<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260924090846 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE booking (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, service_type VARCHAR(255) NOT NULL, departure_location VARCHAR(255) NOT NULL, destination VARCHAR(255) NOT NULL, departure_date DATE NOT NULL, departure_time TIME(0) WITHOUT TIME ZONE NOT NULL, return_date DATE DEFAULT NULL, return_time TIME(0) WITHOUT TIME ZONE DEFAULT NULL, is_round_trip BOOLEAN NOT NULL, passenger_count INT NOT NULL, luggage_count INT NOT NULL, has_baby_seat BOOLEAN NOT NULL, has_pmr_assistance BOOLEAN NOT NULL, vehicle_type VARCHAR(255) NOT NULL, has_mineral_water BOOLEAN NOT NULL, full_name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, whatsapp VARCHAR(50) DEFAULT NULL, comment TEXT DEFAULT NULL, company_name VARCHAR(255) DEFAULT NULL, company_department VARCHAR(255) DEFAULT NULL, cost_center VARCHAR(255) DEFAULT NULL, file_reference VARCHAR(255) DEFAULT NULL, is_company_invoicing BOOLEAN NOT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE booking');
    }
}
